/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/office_chair.glb
Author: Red Fox / nokillnando (https://sketchfab.com/nokillnando)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-b228a29fa84544c2be501c295653ffe7
Title: Office Chair
*/

import { GroupProps } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

import PlasticMesh from './mesh/PlasticMesh'
import MetalMesh from './mesh/MetalMesh'
import ClothMesh from './mesh/ClothMesh'
import LeatherMesh from './mesh/LeatherMesh'

export type OfficeChairProps = GroupProps

export default function OfficeChair({ ...props }: OfficeChairProps) {
  const { nodes, materials } = useGLTF('./office_chair.glb')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <MetalMesh geometry={nodes.OfficeChair_OfficeChairMetal_0.geometry} />
        <PlasticMesh
          geometry={nodes.OfficeChair_OfficeChairPlastic_0.geometry}
        />
        <ClothMesh geometry={nodes.OfficeChair_OfficeChairCloth_0.geometry} />
        <mesh
          geometry={nodes.OfficeChair_OfficeChairLeather_0.geometry}
          material={materials.OfficeChairLeather}
        />
        <LeatherMesh
          geometry={nodes.OfficeChair_OfficeChairLeather_0.geometry}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./office_chair.glb')
